apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-platform-test
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/sdouglas1-tenant/multi-platform-test/multi-platform-test@sha256:fcdb29d03d863af6ccba912775b7b2901abf0b02549898baf572d323ebca9ca4
        name: my-go
        resources: {}
status: {}
